// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CozmoAnim
{

using global::System;
using global::FlatBuffers;

public struct LiftHeight : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_11_1(); }
  public static LiftHeight GetRootAsLiftHeight(ByteBuffer _bb) { return GetRootAsLiftHeight(_bb, new LiftHeight()); }
  public static LiftHeight GetRootAsLiftHeight(ByteBuffer _bb, LiftHeight obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public LiftHeight __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint TriggerTimeMs { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint DurationTimeMs { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public byte HeightMm { get { int o = __p.__offset(8); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public byte HeightVariabilityMm { get { int o = __p.__offset(10); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }

  public static Offset<CozmoAnim.LiftHeight> CreateLiftHeight(FlatBufferBuilder builder,
      uint triggerTime_ms = 0,
      uint durationTime_ms = 0,
      byte height_mm = 0,
      byte heightVariability_mm = 0) {
    builder.StartTable(4);
    LiftHeight.AddDurationTimeMs(builder, durationTime_ms);
    LiftHeight.AddTriggerTimeMs(builder, triggerTime_ms);
    LiftHeight.AddHeightVariabilityMm(builder, heightVariability_mm);
    LiftHeight.AddHeightMm(builder, height_mm);
    return LiftHeight.EndLiftHeight(builder);
  }

  public static void StartLiftHeight(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddTriggerTimeMs(FlatBufferBuilder builder, uint triggerTimeMs) { builder.AddUint(0, triggerTimeMs, 0); }
  public static void AddDurationTimeMs(FlatBufferBuilder builder, uint durationTimeMs) { builder.AddUint(1, durationTimeMs, 0); }
  public static void AddHeightMm(FlatBufferBuilder builder, byte heightMm) { builder.AddByte(2, heightMm, 0); }
  public static void AddHeightVariabilityMm(FlatBufferBuilder builder, byte heightVariabilityMm) { builder.AddByte(3, heightVariabilityMm, 0); }
  public static Offset<CozmoAnim.LiftHeight> EndLiftHeight(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CozmoAnim.LiftHeight>(o);
  }
};


}
